# Generated by Django 3.2.3 on 2021-05-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
